# Merging Goodreads to NYT data

In [1]:
import pandas as pd

# Importing NYT Bestseller data

In [2]:
books = pd.read_csv('books.csv')

In [3]:
books

,Unnamed: 0,title,author,min_rank,max_weeks_on_list,title_url
0,0,ODD HOURS,Dean R Koontz,1,6,ODD+HOURS
1,1,THE HOST,Stephenie Meyer,10,9,THE+HOST
2,2,LOVE THE ONE YOU'RE WITH,Emily Giffin,10,9,LOVE+THE+ONE+YOU%27RE+WITH
3,3,THE FRONT,Patricia Cornwell,14,3,THE+FRONT
4,4,SNUFF,Chuck Palahniuk,10,3,SNUFF
5,5,SUNDAYS AT TIFFANYâ€™S,James Patterson and Gabrielle Charbonnet,10,8,SUNDAYS+AT+TIFFANY%27S
6,6,PHANTOM PREY,John Sandford,12,5,PHANTOM+PREY
7,7,SWINE NOT?,Jimmy Buffett,16,2,SWINE+NOT
8,8,CARELESS IN RED,Elizabeth George,12,4,CARELESS+IN+RED
9,9,THE WHOLE TRUTH,David Baldacci,10,6,THE+WHOLE+TRUTH
10,10,INVINCIBLE,Troy Denning,11,3,INVINCIBLE
11,11,BRIGHT SHINY MORNING,James Frey,12,2,BRIGHT+SHINY+MORNING
12,12,THE ART OF RACING IN THE RAIN,Garth Stein,13,5,THE+ART+OF+RACING+IN+THE+RAIN
13,13,TWENTY WISHES,Debbie Macomber,14,4,TWENTY+WISHES
14,14,THE STEEL WAVE,Jeff Shaara,15,2,THE+STEEL+WAVE
15,15,EXECUTIVE PRIVILEGE,Phillip Margolin,16,0,EXECUTIVE+PRIVILEGE
16,16,UNACCUSTOMED EARTH,Jhumpa Lahiri,17,0,UNACCUSTOMED+EARTH
17,17,NETHERLAND,Joseph O'Neill,18,0,NETHERLAND
18,18,THE APPEAL,John Grisham,16,0,THE+APPEAL
19,19,INDIANA JONES AND THE KINGDOM OF THE CRYSTAL S...,James Rollins,20,0,INDIANA+JONES+AND+THE+KINGDOM+OF+THE+CRYSTAL+S...
20,20,BLOOD NOIR,Laurell K Hamilton,1,4,BLOOD+NOIR
21,25,CHASING HARRY WINSTON,Lauren Weisberger,10,9,CHASING+HARRY+WINSTON
22,27,DEVIL MAY CARE,Sebastian Faulks,11,3,DEVIL+MAY+CARE
23,30,SHADOW OF POWER,Steve Martini,11,2,SHADOW+OF+POWER
24,36,BLUE SMOKE AND MURDER,Elizabeth Lowell,17,0,BLUE+SMOKE+AND+MURDER
25,38,THE ENCHANTRESS OF FLORENCE,Salman Rushdie,18,0,THE+ENCHANTRESS+OF+FLORENCE
26,40,NOTHING TO LOSE,Lee Child,1,5,NOTHING+TO+LOSE
27,42,PLAGUE SHIP,Clive Cussler with Jack Du Brul,13,4,PLAGUE+SHIP
28,48,DEATH AND HONOR,W E B Griffin and William E Butterworth IV,11,2,DEATH+AND+HONOR
29,55,THE SPIES OF WARSAW,Alan Furst,16,1,THE+SPIES+OF+WARSAW
...,...,...,...,...,...,...
2298,10064,THE CROOKED STAIRCASE,Dean Koontz,10,3,THE+CROOKED+STAIRCASE
2299,10065,WARLIGHT,Michael Ondaatje,15,4,WARLIGHT
2300,10073,LOVE AND RUIN,Paula McLain,14,1,LOVE+AND+RUIN
2301,10075,THE CAST,Danielle Steel,1,3,THE+CAST
2302,10078,BY INVITATION ONLY,Dorothea Benton Frank,4,3,BY+INVITATION+ONLY
2303,10088,HOW TO WALK AWAY,Katherine Center,14,1,HOW+TO+WALK+AWAY
2304,10090,THE OUTSIDER,Stephen King,1,7,THE+OUTSIDER
2305,10095,BEACH HOUSE REUNION,Mary Alice Monroe,6,1,BEACH+HOUSE+REUNION
2306,10104,THE FAVORITE SISTER,Jessica Knoll,15,1,THE+FAVORITE+SISTER
2307,10106,SHELTER IN PLACE,Nora Roberts,14,6,SHELTER+IN+PLACE
2308,10107,THE GRAY GHOST,Clive Cussler and Robin Burcell,3,3,THE+GRAY+GHOST
2309,10108,THE DEATH OF MRS. WESTAWAY,Ruth Ware,4,6,THE+DEATH+OF+MRS.+WESTAWAY
2310,10109,TO THE MOON AND BACK,Karen Kingsbury,5,1,TO+THE+MOON+AND+BACK
2311,10120,THE PRESIDENT IS MISSING,Bill Clinton and James Patterson,1,5,THE+PRESIDENT+IS+MISSING
2312,10124,BRIEF CASES,Jim Butcher,5,1,BRIEF+CASES
2313,10127,WHEN LIFE GIVES YOU LULULEMONS,Lauren Weisberger,10,5,WHEN+LIFE+GIVES+YOU+LULULEMONS
2314,10128,US AGAINST YOU,Fredrik Backman,9,1,US+AGAINST+YOU
2315,10129,TURBULENCE,Stuart Woods,10,1,TURBULENCE
2316,10130,SOMETHING IN THE WATER,Catherine Steadman,11,5,SOMETHING+IN+THE+WATER
2317,10132,THERE THERE,Tommy Orange,12,5,THERE+THERE
2318,10137,TOM CLANCY LINE OF SIGHT,Mike Maden,11,4,TOM+CLANCY+LINE+OF+SIGHT
2319,10138,THE PHARAOH KEY,Douglas Preston and Lincoln Child,15,2,THE+PHARAOH+KEY
2320,10143,BEFORE THE STORM,Christie Golden,9,1,BEFORE+THE+STORM
2321,10147,A PLACE FOR US,Fatima Farheen Mirza,13,1,A+PLACE+FOR+US
2322,10151,THE PERFECT COUPLE,Elin Hilderbrand,2,3,THE+PERFECT+COUPLE
2323,10161,THE SKAAR INVASION,Terry Brooks,12,1,THE+SKAAR+INVASION
2324,10162,BRING ME BACK,BA Paris,13,1,BRING+ME+BACK
2325,10166,ALL WE EVER WANTED,Emily Giffin,2,2,ALL+WE+EVER+WANTED
2326,10181,SPYMASTER,Brad Thor,2,1,SPYMASTER
2327,10194,THE LAST TIME I LIED,Riley Sager,15,1,THE+LAST+TIME+I+LIED

In [8]:
books.rename(columns={'title': 'title_query'}, inplace=True)

In [9]:
books.head()

,Unnamed: 0,title_query,author,min_rank,max_weeks_on_list,title_url
0,0,ODD HOURS,Dean R Koontz,1,6,ODD+HOURS
1,1,THE HOST,Stephenie Meyer,10,9,THE+HOST
2,2,LOVE THE ONE YOU'RE WITH,Emily Giffin,10,9,LOVE+THE+ONE+YOU%27RE+WITH
3,3,THE FRONT,Patricia Cornwell,14,3,THE+FRONT
4,4,SNUFF,Chuck Palahniuk,10,3,SNUFF

In [20]:
books.shape

(2328, 6)

# Importing Goodreads Data

In [4]:
goodreads = pd.read_csv('goodreads_data.csv')

In [5]:
goodreads

,Unnamed: 0,author,author_id,average_rating,book_id,ratings_count,title,title_query,title_match,gender,num_pages
0,0,Allegra Goodman,16264.0,3.31,7632696.0,11945.0,THE COOKBOOK COLLECTOR,THE COOKBOOK COLLECTOR,True,NaN,NaN
1,1,Alexander McCall Smith,4738.0,3.72,13642130.0,3932.0,THE UNCOMMON APPEAL OF CLOUDS,THE UNCOMMON APPEAL OF CLOUDS,True,male,288
2,2,Cathleen Schine,127216.0,2.90,6670347.0,7598.0,THE THREE WEISSMANNS OF WESTPORT,THE THREE WEISSMANNS OF WESTPORT,True,female,295
3,3,Amanda Quick,42211.0,4.03,6908832.0,7193.0,BURNING LAMP,BURNING LAMP,True,None,340
4,4,Jennifer Chiaverini,11630.0,3.86,6654118.0,3777.0,THE ALOHA QUILT,THE ALOHA QUILT,True,female,NaN
5,5,Louise Penny,194243.0,4.20,16045144.0,35792.0,THE BEAUTIFUL MYSTERY,THE BEAUTIFUL MYSTERY,True,NaN,NaN
6,6,Tess Gerritsen,18149.0,4.10,2653622.0,29612.0,THE KEEPSAKE,THE KEEPSAKE,True,female,NaN
7,7,Patrick Rothfuss,108424.0,4.58,1215032.0,346792.0,THE WISE MAN'S FEAR,THE WISE MAN'S FEAR,True,male,NaN
8,8,Kate Morton,615274.0,4.05,21104828.0,81203.0,THE LAKE HOUSE,THE LAKE HOUSE,True,None,495
9,9,Susan Elizabeth Phillips,41313.0,4.08,8437379.0,19182.0,CALL ME IRRESISTIBLE,CALL ME IRRESISTIBLE,True,female,385
10,10,Christina Baker Kline,157146.0,3.87,30255942.0,47666.0,A PIECE OF THE WORLD,A PIECE OF THE WORLD,True,female,352
11,11,Debbie Macomber,11349.0,4.04,16156294.0,11497.0,ROSE HARBOR IN BLOOM,ROSE HARBOR IN BLOOM,True,female,NaN
12,12,Roma Downey,435808.0,4.24,15789630.0,491.0,THE STORY OF GOD AND ALL OF US,THE STORY OF GOD AND ALL OF US,True,None,352
13,13,James Lee Burke,7031.0,4.00,6238661.0,4559.0,RAIN GODS,RAIN GODS,True,male,434
14,14,Johanna Lindsey,29542.0,3.98,7125012.0,6079.0,THAT PERFECT SOMEONE,THAT PERFECT SOMEONE,True,female,372
15,15,Suzanne Collins,153394.0,4.33,2767052.0,5629612.0,THE GAMES,THE GAMES,True,female,374
16,16,James Patterson,3780.0,3.92,14781501.0,29467.0,NYPD RED,NYPD RED,True,male,512
17,17,Lauren Wilkinson,17287509.0,3.96,40274582.0,82.0,AN AMERICAN SPY,AN AMERICAN SPY,True,female,304
18,18,Dean Koontz,9355.0,4.14,15722284.0,16771.0,SAINT ODD,SAINT ODD,True,None,NaN
19,19,Ruth Ware,9013543.0,3.68,27834600.0,150137.0,"IN A DARK, DARK WOOD","IN A DARK, DARK WOOD",True,None,NaN
20,20,Richard Paul Evans,46097.0,4.15,23058989.0,10312.0,THE MISTLETOE PROMISE,THE MISTLETOE PROMISE,True,male,NaN
21,21,Sandra Brown,6218.0,3.96,29203612.0,18194.0,STING,STING,True,female,NaN
22,22,Iris Johansen,32498.0,4.08,23847964.0,3997.0,SHADOW PLAY,SHADOW PLAY,True,None,NaN
23,23,Wally Lamb,3505.0,3.81,3086160.0,53248.0,THE HOUR I FIRST BELIEVED,THE HOUR I FIRST BELIEVED,True,male,740
24,24,Robert Galbraith,383606.0,4.22,40611999.0,129310.0,CAREER OF EVIL,CAREER OF EVIL,True,female,NaN
25,25,Dan Simmons,2687.0,4.02,11279.0,17233.0,THE NIGHT SEASON,THE NIGHT SEASON,True,NaN,NaN
26,26,Mark Helprin,8146.0,3.47,13391073.0,3365.0,IN SUNLIGHT AND IN SHADOW,IN SUNLIGHT AND IN SHADOW,True,male,705
27,27,Richard Castle,1953433.0,3.97,17336666.0,8793.0,DEADLY HEAT,DEADLY HEAT,True,male,291
28,28,Leila Sales,3390621.0,3.69,10637697.0,5895.0,PAST PERFECT,PAST PERFECT,True,female,306
29,29,Rainbow Rowell,4208569.0,3.55,18081809.0,139762.0,LANDLINE,LANDLINE,True,None,310
...,...,...,...,...,...,...,...,...,...,...,...
2267,2270,Steve Berry,3621.0,3.89,3124122.0,16058.0,THE CHARLEMAGNE PURSUIT,THE CHARLEMAGNE PURSUIT,True,male,None
2268,2271,Alexander McCall Smith,4738.0,4.11,17345190.0,11281.0,THE MINOR ADJUSTMENT BEAUTY SALON,THE MINOR ADJUSTMENT BEAUTY SALON,True,male,242
2269,2272,Michael Brandman,4678962.0,3.97,13573363.0,5351.0,ROBERT B PARKER'S FOOL ME TWICE,ROBERT B PARKER'S FOOL ME TWICE,True,male,None
2270,2273,Danielle Steel,14255.0,3.94,22551744.0,6525.0,PRODIGAL SON,PRODIGAL SON,True,female,318
2271,2274,Kristin Hannah,54493.0,4.56,21853621.0,478887.0,THE NIGHTINGALE,THE NIGHTINGALE,True,female,440
2272,2275,Randy Wayne White,27932.0,3.65,11890814.0,1726.0,CHASING MIDNIGHT,CHASING MIDNIGHT,True,male,336
2273,2276,Lauren Oliver,2936493.0,3.91,6482837.0,267963.0,BEFORE THE FALL,BEFORE THE FALL,True,female,473
2274,2277,Elizabeth Strout,97313.0,3.51,25893709.0,90207.0,MY NAME IS LUCY BARTON,MY NAME IS LUCY BARTON,True,female,193
2275,2278,Janet Evanovich,2384.0,3.79,28686830.0,34971.0,TURBO TWENTY-THREE,TURBO TWENTY-THREE,True,female,288
2276,2279,Maeve Binchy,3532.0,3.66,18050097.0,9412.0,CHESTNUT STREET,CHESTNUT STREET,True,female,368
2277,2280,Elin Hilderbrand,88301.0,3.83,18656006.0,27292.0,THE MATCHMAKER,THE MATCHMAKER,True,None,368
2278,2281,Robert Galbraith,383606.0,3.85,16160797.0,410403.0,THE CUCKOO'S CALLING,THE CUCKOO'S CALLING,True,female,455
2279,2282,John Hart,47072.0,4.09,10024937.0,12419.0,IRON HOUSE,IRON HOUSE,True,male,421
2280,2283,B.A. Paris,14425604.0,3.90,31450633.0,54055.0,THE BREAKDOWN,THE BREAKDOWN,True,None,328
2281,2284,Alison Lurie,2046.0,3.74,202897.0,8702.0,FOREIGN AFFAIRS,FOREIGN AFFAIRS,True,female,292
2282,2285,Jeff Lindsay,10482.0,3.57,17262204.0,7274.0,THE FINAL CUT,THE FINAL CUT,True,None,352
2283,2286,Tim Dorsey,27017.0,4.13,6672751.0,2278.0,GATOR A-GO-GO,GATOR A-GO-GO,True,male,336
2284,2287,Alex Berenson,195905.0,4.05,15815367.0,4523.0,THE NIGHT RANGER,THE NIGHT RANGER,True,None,387
2285,2288,Jacqueline Winspear,5023.0,3.69,18695272.0,6250.0,THE CARE AND MANAGEMENT OF LIES,THE CARE AND MANAGEMENT OF LIES,True,None,319
2286,2289,Vince Flynn,14989.0,4.32,3313418.0,43173.0,EXTREME MEASURES,EXTREME MEASURES,True,male,448
2287,2290,Emma Straub,1983563.0,3.15,18641982.0,56420.0,THE VACATIONERS,THE VACATIONERS,True,female,292
2288,2291,Robin Hobb,25307.0,4.51,40610956.0,24364.0,FOOL'S QUEST,FOOL'S QUEST,True,female,757
2289,2292,Kristin Hannah,54493.0,4.33,34912895.0,171535.0,THE GREAT ALONE,THE GREAT ALONE,True,female,None
2290,2293,Rita Mae Brown,23511.0,3.74,3190662.0,1998.0,SANTA CLAWED,SANTA CLAWED,True,female,237
2291,2294,Jennifer Weiner,9212.0,3.50,6066819.0,55509.0,FRIENDS FOREVER,FRIENDS FOREVER,True,female,368
2292,2295,Oliver PÃ¶tzsch,2783820.0,3.73,9496240.0,62414.0,HANGMAN,HANGMAN,True,male,448
2293,2296,Terri Blackstock,19811.0,4.16,6322079.0,4947.0,INTERVENTION,INTERVENTION,True,female,324
2294,2297,Christie Golden,7710.0,4.06,13260060.0,3463.0,JAINA PROUDMOORE: TIDES OF WAR,JAINA PROUDMOORE: TIDES OF WAR,True,female,352
2295,2298,Mary Higgins Clark,99044.0,3.68,6629816.0,8586.0,THE SHADOW OF YOUR SMILE,THE SHADOW OF YOUR SMILE,True,female,319
2296,2299,Ken Follett,3447.0,4.32,12959233.0,106800.0,WINTER OF THE WORLD,WINTER OF THE WORLD,True,None,940

In [10]:
df = pd.merge(books, goodreads, how='left', on='title_query')

In [29]:
df.head()

,Unnamed: 0_x,title_query,author_x,min_rank,max_weeks_on_list,title_url,Unnamed: 0_y,author_y,author_id,average_rating,book_id,ratings_count,title,title_match,gender,num_pages
0,0,ODD HOURS,Dean R Koontz,1,6,ODD+HOURS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,THE HOST,Stephenie Meyer,10,9,THE+HOST,779.0,Stephenie Meyer,941441.0,3.84,1656001.0,819307.0,THE HOST,True,female,620
2,1,THE HOST,Stephenie Meyer,10,9,THE+HOST,1877.0,Stephenie Meyer,941441.0,3.84,1656001.0,819325.0,THE HOST,True,female,620
3,2,LOVE THE ONE YOU'RE WITH,Emily Giffin,10,9,LOVE+THE+ONE+YOU%27RE+WITH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,THE FRONT,Patricia Cornwell,14,3,THE+FRONT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.shape

(2879, 16)

# Cleaning out some of the duplicates do to index numbers

In [13]:
data = df[['title_query','author_x','author_y','min_rank', 'max_weeks_on_list','author_id', 'average_rating', 'book_id', 'ratings_count', 'title', 'title_match', 'gender', 'num_pages']].drop_duplicates()

In [30]:
data.head()

,title_query,author_nyt,author_gr,min_rank,max_weeks_on_list,author_id,average_rating,book_id,ratings_count,title,gender,num_pages
0,ODD HOURS,Dean R Koontz,NaN,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,THE HOST,Stephenie Meyer,Stephenie Meyer,10,9,941441.0,3.84,1656001.0,819307.0,THE HOST,female,620
2,THE HOST,Stephenie Meyer,Stephenie Meyer,10,9,941441.0,3.84,1656001.0,819325.0,THE HOST,female,620
3,LOVE THE ONE YOU'RE WITH,Emily Giffin,NaN,10,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,THE FRONT,Patricia Cornwell,NaN,14,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
data.shape

(2606, 13)

In [21]:
data = df[['title_query','author_x','author_y','min_rank', 'max_weeks_on_list','author_id', 'average_rating', 'book_id', 'ratings_count', 'title','title_match', 'gender', 'num_pages']].drop_duplicates()

In [22]:
data.shape

(2606, 12)

# Rename columns so we know which were the NYT authors and which were the goodreads authors

In [25]:
data.rename(columns={'author_x': 'author_nyt'}, inplace=True)

In [26]:
data.rename(columns={'author_y': 'author_gr'}, inplace=True)

In [27]:
data

,title_query,author_nyt,author_gr,min_rank,max_weeks_on_list,author_id,average_rating,book_id,ratings_count,title,gender,num_pages
0,ODD HOURS,Dean R Koontz,NaN,1,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,THE HOST,Stephenie Meyer,Stephenie Meyer,10,9,941441.0,3.84,1656001.0,819307.0,THE HOST,female,620
2,THE HOST,Stephenie Meyer,Stephenie Meyer,10,9,941441.0,3.84,1656001.0,819325.0,THE HOST,female,620
3,LOVE THE ONE YOU'RE WITH,Emily Giffin,NaN,10,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,THE FRONT,Patricia Cornwell,NaN,14,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,SNUFF,Chuck Palahniuk,Chuck Palahniuk,10,3,2546.0,3.19,1840511.0,50665.0,SNUFF,male,NaN
6,SUNDAYS AT TIFFANYâ€™S,James Patterson and Gabrielle Charbonnet,NaN,10,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,PHANTOM PREY,John Sandford,NaN,12,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,SWINE NOT?,Jimmy Buffett,NaN,16,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CARELESS IN RED,Elizabeth George,NaN,12,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,THE WHOLE TRUTH,David Baldacci,David Baldacci,10,6,9291.0,4.01,2260637.0,25958.0,THE WHOLE TRUTH,male,NaN
11,INVINCIBLE,Troy Denning,StanisÅ‚aw Lem,11,3,10991.0,4.18,251633.0,4928.0,INVINCIBLE,male,None
12,INVINCIBLE,Troy Denning,StanisÅ‚aw Lem,11,3,10991.0,4.18,251633.0,4929.0,INVINCIBLE,male,None
13,BRIGHT SHINY MORNING,James Frey,James Frey,12,2,822.0,3.81,2179832.0,12555.0,BRIGHT SHINY MORNING,NaN,NaN
14,THE ART OF RACING IN THE RAIN,Garth Stein,Garth Stein,13,5,194531.0,4.20,3153910.0,395338.0,THE ART OF RACING IN THE RAIN,male,321
15,TWENTY WISHES,Debbie Macomber,NaN,14,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,THE STEEL WAVE,Jeff Shaara,Jeff Shaara,15,2,14655.0,4.22,2047408.0,5408.0,THE STEEL WAVE,male,493
17,EXECUTIVE PRIVILEGE,Phillip Margolin,Phillip Margolin,16,0,7153.0,3.81,2396743.0,6025.0,EXECUTIVE PRIVILEGE,male,358
18,UNACCUSTOMED EARTH,Jhumpa Lahiri,NaN,17,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NETHERLAND,Joseph O'Neill,Joseph O'Neill,18,0,389474.0,3.41,2615008.0,16516.0,NETHERLAND,male,269
20,THE APPEAL,John Grisham,John Grisham,16,0,721.0,3.59,1248179.0,45355.0,THE APPEAL,male,NaN
21,INDIANA JONES AND THE KINGDOM OF THE CRYSTAL S...,James Rollins,NaN,20,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,BLOOD NOIR,Laurell K Hamilton,Laurell K. Hamilton,1,4,9550.0,3.85,2149535.0,36046.0,BLOOD NOIR,female,NaN
23,CHASING HARRY WINSTON,Lauren Weisberger,Lauren Weisberger,10,9,3490.0,3.33,426775.0,72395.0,CHASING HARRY WINSTON,female,288
24,DEVIL MAY CARE,Sebastian Faulks,Elizabeth Peters,11,3,16549.0,3.87,32138.0,2357.0,DEVIL MAY CARE,female,352
25,SHADOW OF POWER,Steve Martini,Erin Hunter,11,2,27498.0,4.30,3342493.0,13652.0,SHADOW OF POWER,female,316
26,BLUE SMOKE AND MURDER,Elizabeth Lowell,Elizabeth Lowell,17,0,19051.0,3.88,2183985.0,3276.0,BLUE SMOKE AND MURDER,female,404
27,THE ENCHANTRESS OF FLORENCE,Salman Rushdie,Salman Rushdie,18,0,3299.0,3.58,1317696.0,15710.0,THE ENCHANTRESS OF FLORENCE,male,359
28,NOTHING TO LOSE,Lee Child,Lee Child,1,5,5091.0,3.91,2211221.0,45190.0,NOTHING TO LOSE,male,None
29,PLAGUE SHIP,Clive Cussler with Jack Du Brul,Clive Cussler,13,4,18411.0,4.04,2055151.0,9658.0,PLAGUE SHIP,male,515
...,...,...,...,...,...,...,...,...,...,...,...,...
2848,BY INVITATION ONLY,Dorothea Benton Frank,Dorothea Benton Frank,4,3,36935.0,3.85,37955592.0,7413.0,BY INVITATION ONLY,female,None
2849,HOW TO WALK AWAY,Katherine Center,Katherine Center,14,1,409113.0,4.09,36249638.0,19296.0,HOW TO WALK AWAY,NaN,NaN
2850,THE OUTSIDER,Stephen King,S.E. Hinton,1,7,762707.0,4.08,231804.0,787721.0,THE OUTSIDER,female,192
2851,THE OUTSIDER,Stephen King,S.E. Hinton,1,7,762707.0,4.08,231804.0,787751.0,THE OUTSIDER,female,192
2852,BEACH HOUSE REUNION,Mary Alice Monroe,Mary Alice Monroe,6,1,5080.0,4.14,36373870.0,3444.0,BEACH HOUSE REUNION,female,389
2853,THE FAVORITE SISTER,Jessica Knoll,Jessica Knoll,15,1,6464799.0,3.10,36967019.0,11126.0,THE FAVORITE SISTER,female,375
2854,SHELTER IN PLACE,Nora Roberts,Nora Roberts,14,6,625.0,4.26,36425796.0,18066.0,SHELTER IN PLACE,female,438
2855,SHELTER IN PLACE,Nora Roberts,Nora Roberts,14,6,625.0,4.26,36425796.0,18068.0,SHELTER IN PLACE,female,438
2856,THE GRAY GHOST,Clive Cussler and Robin Burcell,NaN,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2857,THE DEATH OF MRS. WESTAWAY,Ruth Ware,NaN,4,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2858,TO THE MOON AND BACK,Karen Kingsbury,Jill Mansell,5,1,23625.0,4.00,8421219.0,10790.0,TO THE MOON AND BACK,NaN,NaN
2859,THE PRESIDENT IS MISSING,Bill Clinton and James Patterson,Bill Clinton,1,5,5944.0,3.87,35097255.0,52697.0,THE PRESIDENT IS MISSING,NaN,NaN
2860,BRIEF CASES,Jim Butcher,Jim Butcher,5,1,10746.0,4.42,12183815.0,8237.0,BRIEF CASES,male,516
2861,WHEN LIFE GIVES YOU LULULEMONS,Lauren Weisberger,Lauren Weisberger,10,5,3490.0,3.74,36373647.0,25285.0,WHEN LIFE GIVES YOU LULULEMONS,female,NaN
2862,US AGAINST YOU,Fredrik Backman,Fredrik Backman,9,1,6485178.0,4.37,36373463.0,34612.0,US AGAINST YOU,None,448
2863,US AGAINST YOU,Fredrik Backman,Fredrik Backman,9,1,6485178.0,4.37,36373463.0,34631.0,US AGAINST YOU,None,448
2864,TURBULENCE,Stuart Woods,NaN,10,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2865,SOMETHING IN THE WATER,Catherine Steadman,NaN,11,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2866,THERE THERE,Tommy Orange,NaN,12,5,NaN,NaN,NaN,NaN,THERE THERE,None,NaN
2867,TOM CLANCY LINE OF SIGHT,Mike Maden,Mike Maden,11,4,7025886.0,3.97,42732540.0,2783.0,TOM CLANCY LINE OF SIGHT,male,528
2868,THE PHARAOH KEY,Douglas Preston and Lincoln Child,Douglas Preston,15,2,12577.0,3.75,36342060.0,3794.0,THE PHARAOH KEY,male,NaN
2869,BEFORE THE STORM,Christie Golden,Diane Chamberlain,9,1,93345.0,4.04,2589061.0,11309.0,BEFORE THE STORM,NaN,NaN
2870,A PLACE FOR US,Fatima Farheen Mirza,Fatima Farheen Mirza,13,1,16984671.0,4.16,36840397.0,17022.0,A PLACE FOR US,None,385
2871,THE PERFECT COUPLE,Elin Hilderbrand,Elin Hilderbrand,2,3,88301.0,4.01,34840184.0,29226.0,THE PERFECT COUPLE,None,480
2872,THE SKAAR INVASION,Terry Brooks,Terry Brooks,12,1,9629.0,4.15,36196054.0,1123.0,THE SKAAR INVASION,male,None
2873,BRING ME BACK,BA Paris,NaN,13,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2874,ALL WE EVER WANTED,Emily Giffin,Emily Giffin,2,2,13370.0,3.90,36344555.0,48244.0,ALL WE EVER WANTED,female,None
2875,SPYMASTER,Brad Thor,Joanna Bourne,2,1,486041.0,4.02,959745.0,6244.0,SPYMASTER,female,373
2877,THE LAST TIME I LIED,Riley Sager,Riley Sager,15,1,15263414.0,4.09,36626748.0,24647.0,THE LAST TIME I LIED,None,None
2878,THE LAST TIME I LIED,Riley Sager,Riley Sager,15,1,15263414.0,4.09,36626748.0,24654.0,THE LAST TIME I LIED,None,None

# Export to CSV

In [28]:
data.to_csv("data.csv")